### PR TITLE
update for release 2.1.2

### PR DESCRIPTION
**Pull request by felixcheung**
updating steps here https://github.com/apache/spark-website/pull/69/files#diff-12257e3523e2ce22fccd80687597e7cd

site/docs/ for the release is in a different PR.

### CODE REVIEW

**Comment by felixcheung** [comment]
@srowen @holdenk

**Comment by felixcheung** [comment]
I couldnt' get the doc build to work on 2.1.2 source release for some reasons, if Holden you have the doc from the RC/release please get this in under site/docs/2.1.2

```
[info] Constructing Javadoc information...
[error] /home/user/spark-2.1.2/core/target/java/org/apache/spark/serializer/SerializationDebugger.java:159: error: cannot find symbol
[error]   static private  org.apache.spark.serializer.SerializationDebugger.ObjectStreamClassReflection reflect ()  { throw new RuntimeException(); }
[error]                                                                    ^
[error]   symbol:   class ObjectStreamClassReflection
[error]   location: class SerializationDebugger
[error] /home/user/spark-2.1.2/core/target/java/org/apache/spark/serializer/SerializationDebugger.java:22: error: class SerializationDebugger is already defined in package org.apache.spark.serializer
[error]   static private  class SerializationDebugger {
[error]                   ^
```

File: documentation.md [hunk 1]
```diff
@@ -12,6 +12,8 @@ navigation:
 <p>Setup instructions, programming guides, and other documentation are available for each stable version of Spark below:</p>
 
 <ul>
+  <li><a href="{{site.baseurl}}/docs/2.1.2/">Spark 2.1.2</a></li>
```
Comment (srowen) [inline documentation.md:15]: Include 2.2.0 while you're at it? not sure why this hasn't been updated.

File: site/sitemap.xml [hunk 2]
```diff
@@ -660,27 +668,27 @@
   <changefreq>weekly</changefreq>
 </url>
 <url>
-  <loc>https://spark.apache.org/mllib/</loc>
+  <loc>https://spark.apache.org/sql/</loc>
```
Comment (srowen) [inline site/sitemap.xml:671]: I'm not sure why this keeps changing order. It doesn't matter, so don't spend time on it, but do you have the latest jekyll etc?

**Review by srowen — COMMENTED** [review]
Changes so far look fine to me.

**Comment by holdenk** [comment]
@felixcheung Thanks for doing this part, I'll grab the docs we voted on and copy them in a separate PR - sound good?

File: documentation.md (hunk 1 above)
Comment (felixcheung) [reply documentation.md:15]: I think the idea is this is the list of releases except the latest.
The link to this page under the "Documentation" tab that says "Older Versions and Other Resources"

But I guess it could be a bit confusing?

File: site/sitemap.xml (hunk 2 above)
Comment (felixcheung) [reply site/sitemap.xml:671]: Hmm, that I don't know. I did try to update jekyll + all other packages etc before running this.
I could just reverse this hunk, which is simple to do...

**Comment by holdenk** [comment]
Now that the docs are in I've merged this into the asf-site branch.

**Comment by felixcheung** [comment]
thanks! closing this

**Comment by felixcheung** [comment]
testing this, I noticed that the Direct Download link on the Downloads page is invalid

https://spark.apache.org/downloads.html

what's process of getting stuff uploaded to https://d3kbcqa49mib13.cloudfront.net/?

**Comment by holdenk** [comment]
I've reached out to private@ about that, honestly I have no idea. I had thought it was caching in front of the ASF mirrors but that's pretty clearly not the case.

**Comment by holdenk** [comment]
I'm hoping its just a copy that anyone on the PMC can do.

**Comment by felixcheung** [comment]
I think it's a s3 containing copies of all releases....

**Comment by holdenk** [comment]
In that case hopefully all of the PMC has access S3 keys, but that's a discussion for private@ by the PMC folks.
